### ISSUE TITLE
Scene shadow

### ISSUE THREAD

**Issue by pontusab** [expo/ex-navigation#272]
How do I remove the shadow? I can see the styles within the component **ExNavigationStackItem** but I do not know how to pass props to override these values:

```javascript
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.4,
    shadowRadius: 10,
```
 
![bitmap](https://cloud.githubusercontent.com/assets/655158/20573952/8b1bd1fe-b1b2-11e6-9097-412db4422681.png)

**Comment by ox-michaelradionov** [comment]
These shadows also appear for me when I change orientation of the device.

**Comment by tuanngocptn** [comment]
same question.

**Comment by ox-michaelradionov** [comment]
@tuanngocptn 

I finished my project about a year ago, but maybe my fix I used back then will work for you. It relied on me using router `#replace()` method to make transitions.

```
<StackNavigation
  // Route which decides what page should be opened when app starts
  initialRoute="CaptureNavigator"
  defaultRouteConfig={{
    // Override default styles in a hacky way, it's not
    // supported out of the box, but works because we use
    // .replace() for changing routes.
    // https://github.com/exponent/ex-navigation/issues/115
    // https://github.com/exponent/ex-navigation/issues/272
    styles: {
      sceneAnimations: () => ({
        shadowColor: 'transparent',
        shadowRadius: 0,
      }),
    },
  }}
/>
```

**Comment by tuanngocptn** [comment]
nice !!!... thanks you
