### ISSUE TITLE
NavigationExperimental is deprecated on RN43

### ISSUE THREAD

**Issue by sibelius** [expo/ex-navigation#444]
`Warning: NavigationExperimental is deprecated and will be removed in a future version of React Native. The NavigationExperimental views live on in the React-Navigation project, which also makes it easy to declare navigation logic for your app. Learn more at https://reactnavigation.org/`

on RN 43 `NavigationExperimental` is deprecated.

is there any migration guide to react-navigation?

**Comment by vonovak** [comment]
@sibelius does it work on RN 0.43? thanks

**Comment by digitalmaster** [comment]
Also waiting for migration guide... Will probably start to migrate on my own next week if there isnt one by then

**Comment by sibelius** [comment]
https://medium.com/@spencer_carli/migrate-from-exnavigation-to-react-navigation-1af661ec5082

awesome post by @spencercarli
