### ISSUE TITLE
Can only update a mounted or mounting component using immediatelyResetStack

### ISSUE THREAD

**Issue by jsappme** [expo/ex-navigation#468]
I get this warning:

```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState,
 or forceUpdate on an unmounted component. This is a no-op.
```
when using:
`this.props.navigator.immediatelyResetStack([Router.getRoute("tabs")]);`

but not when using:
`this.props.navigator.push(Router.getRoute('tabs'));`

any idea why?

**Comment by mikunpham** [comment]
maybe `this.props.navigator` in `this.props.navigator.immediatelyResetStack` is not the `root` navigator. I think you can try
```javascript
const rootNavigator = this.props.navigation.getNavigator('root')
rootNavigator.immediatelyResetStack([Router.getRoute("tabs")])
```

**Comment by jsappme** [comment]
thanks @mikunpham it's working good.

**Comment by tiaaaa123** [comment]
I'm getting the same issue, but by using replace()

```
try {
      await this.props.actions.authenticate(token);
      this.props.navigator.immediatelyResetStack([Router.getRoute('tabBar')], 0);
} catch (error) {
     this.props.navigator.replace('home');
}
```

I have a stackNavigation ad in the initialRoute, i do this code. While it does the replace to the new route, i get the same warning as the one in this issue.

I tried @mikunpham solution, but it doesn't work. Any idea?

**Comment by vincent-lu** [comment]
I'm having the same problem (with 2.11.2 or 3.0.0). Short of migrating to `react-navigation`. Is there anything we can do?

BTW: the same code worked without problem with Expo 16, but started throwing the warning when I upgraded to Expo 17.

Ping @brentvatne @skevy 

Thanks.

**Comment by calcazar** [comment]
+1
