### ISSUE TITLE
Error on Expo 16.0.0, undefined is not an object ViewPropTypes.style

### ISSUE THREAD

**Issue by bondanherumurti** [expo/ex-navigation#473]
it leaves an error like this

<img width="377" alt="screen shot 2017-05-18 at 6 16 48 pm" src="https://cloud.githubusercontent.com/assets/1384256/26199983/667fb184-3bf6-11e7-809d-ecb50f1b7a34.png">

what i did is actually only putting this after i put the "npm install @expo/ex-navigation --save"

package.json
"@expo/ex-navigation": "^2.12.0"

The only code i add

```
import {
  createRouter,
  NavigationProvider,
  StackNavigation,
} from '@expo/ex-navigation';
```

on main.js and the error comes up

**Comment by skevy** [comment]
I've unpublished 2.12.0, as I didn't realize this was a breaking change.

I've republished the same code as 3.0.0.

Users of React Native 0.43 or below (Expo SDK 16 or below) should continue to use ex-navigation@2.11.2.

Thanks for the report!

**Comment by chetankothari** [comment]
2.11.2 did not work for me. But 2.11.1 worked for me. But thanks for the pointer. This helped me solve the problem.

**Comment by barismercan** [comment]
same problem is with me now. i use genymotion and i create sample react-native project and it works on it. however i clone team's project and it gives this exception? any advice ?

**Comment by cjoshmartin** [comment]
Has this been fix? I am getting this error now

**Comment by barismercan** [comment]
i update the libraries on package.json and it works.  

"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-collapsible": "^0.8.0"

"babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.3",
    "native-base": "^2.1.4",
i dont remember which i update so which you use just update it.

**Comment by SorooshPardazCompany** [comment]
i faced this issue  : 
undefined is not an object ( evaluating 'styles.containerStyle' )

can you help me 

[برنامه نویسی اپلیکیشن اسنپ](https://sorooshpardaz.com/mobile-app-android-ios-programming)
