### ISSUE TITLE
Compatibility with RN 0.47

### ISSUE THREAD

**Issue by leudanielm** [expo/ex-navigation#493]
I have upgraded my codebase to RN 0.47 and I receive this error in the when using the tab navigation. It probably also has to do a lot with the fact that RN 0.47 is paired with React 16.0.0-alpha.12.
![ex-navigation-error](https://user-images.githubusercontent.com/1877088/30031582-657f5aae-9192-11e7-8ef5-aa02a4d0df02.png)

Can anyone point me to the right direction? I am not using something out of ordinary, it's just a TabNavigation component with some TabNavigationItem(s) inside of it.

**Comment by rahulbhankar786** [comment]
I have an issue when using react-native verion 0.50.4 .
![image](https://user-images.githubusercontent.com/33485869/33374072-98bcd028-d52a-11e7-985d-c94106232e51.png)
below is my package.json file details-

"@expo/ex-navigation": "^2.11.2",
		"babel-preset-react-native-stage-0": "^1.0.1",
		"react": "16.0.0",
		"react-native": "0.50.4",
		"react-native-vector-icons": "^4.0.1",
		"react-navigation": "^1.0.0-beta.7"

**Comment by rahulbhankar786** [comment]
use "@expo/ex-navigation": "^3.1.0",
this will solve ur problem.
